### PR TITLE
detect if ansible is available on the guest host

### PR DESCRIPTION
**Pull request by chregu**
otherwise use ansible_local

This is mainly a temporary fix until vagrant-lxc works with ansible_local

But this way we can test the rawbot-virtualization at least on windows

### CODE REVIEW

**Comment by krtek4** [comment]
The idea to use `ansible_local` when `ansible` is not available seems really a great idea waiting for a fix of the lxc issue.

Don't sure I get the `systemd` issue however, it should be installed in the jessie image since it was causing issue on shutdown. @sephii can you confirm the image has no `systemd` ?

Maybe it got pulled by one of the package from dotdeb ?

**Comment by sephii** [comment]
The `systemd` package is installed in the box but sysvinit is used because of the shutdown issue you mentioned.

**Comment by chregu** [comment]
So it's safe to delete that again in the playbook?

It's only a problem when using ansible_local, then it can't restart nginx. It works fine with just ansible

**Comment by sephii** [comment]
I think we could remove the `systemd` package in the base playbook (or we could recreate the base boxes but that's a pain to do).

**Comment by chregu** [comment]
This MR adds
````
+- name: remove systemd
 +  apt: name=systemd state=absent
 +  sudo: yes 
````

so that's already solved ;)

**Comment by chregu** [comment]
It seems to run on windows, with one little change as windows doesn't support symlinks 

I added what to do (copying Vagrantfile instead of symlinking and adding an ansible.cfg to the roles dir) in the README.md. This is only needed if you have developers with Windows, so I don't think this should be the default.

**Comment by chregu** [comment]
Here's the discussed new way.

**Comment by chregu** [comment]
One little thing just came to my mind: There's a BC break now, so if you point your submodule to this new  version, your old project won't work anymore (since the symlink from Vagrantfile to virtualization/rawbot-virtualization/Vagrantfile will be broken).

I see 3 possibilities

1) Just leave it like that and let people realize it when they try to start their vagrant box later
2) Make a Vagrantfile in the old place which spits out some errors and warnings what to do now
3) Keep the old one

2) and 3) have the disadvantage that there is a Vagrantfile, which looks like it's the real thing, but it isn't, it's just a BC placeholder (of course one can include in the file a comment about that)

and for 1). Such BC breaks are not nice (and it should be documented somewhere what to do in that case), but I don't know how many projects you have with this setup and how often you update them.

**Comment by krtek4** [comment]
I took the liberty to make other commits on `master` taking most of your idea.

I fixed the 'ansible_local' thing a bit differently : https://github.com/team-rawbot/rawbot-virtualization/commit/32625674b4eabf3f34949f5944bc4cac51034b32

I think I also found a way to avoid the BC break : https://github.com/team-rawbot/rawbot-virtualization/commit/28d6be0f475d26ae34bc61b3b4f37269bd2e1596

Basically, I didn't renamed the Vagrantfile, I added some compatibility layer in it... Didn't tested it thoroughly for now tho. I'll try that once I merged some other PR in a big test party :P

**Pull request closed without merging**
