### PR TITLE
Avoid 502 Bad Gateway errors with Symfony2

### PR DESCRIPTION
**Pull request by gnutix**

### CODE REVIEW

**Comment by krtek4** [comment]
Can you explain why this is needed ? What I can find on the internet concerning this options does not explain in any way why it could help.

From what I understand it might even hurt performances because nginx waits longer before sending data to the client.

**Comment by gnutix** [comment]
Here are the various sources for this code fix : 

http://stackoverflow.com/a/10697132/389519
http://stackoverflow.com/a/17708324/389519
http://blog.mdnsolutions.com/index.php/nginx-overwrites-symfony-errors-with-502-bad-gateway/
http://ask.webatall.com/nginx/18156_nginx-overwrites-general-symfony-errors-with-502-bad-gateway.html

**Comment by krtek4** [comment]
@gnutix did you read https://github.com/symfony/symfony/issues/8413 ?

What is `ChromePHP` ?

> Closing this issue as this is related to the default configuration of the Symfony Standard Edition, where I've just posted a pull request to disable the FirPHP/ChromePHP loggers by default.

Do you have an up to date Symfony version ?

**Comment by krtek4** [comment]
Seems like this can also lead to issues with Varnish : https://github.com/symfony/symfony/issues/15829

It might be better to solve the issue in your application.

**Comment by gnutix** [comment]
Fixed by removing the firephp/chromephp keys under the monolog configuration in Symfony `app/config` files.

**Pull request closed without merging**
